### ISSUE TITLE
Patcher sorce missing

### ISSUE THREAD

**Issue by erikiorai** [OpenShopChannel/Open-Shop-Channel-Patcher#1]
Hi @kcrpl you frogot putin a open shop channel patcher sorce

**Comment by dakrk** [comment]
The readme says it will be released when the open shop channel has been released

**Comment by erikiorai** [comment]
Ok

**Comment by KcrPL** [comment]
Hi,

Please read [README.md](https://github.com/OpenShopChannel/Open-Shop-Channel-Patcher/blob/master/README.md) carefully. Open Shop Channel is still not available to public therefore the source code of the patcher is not available to public because it would reveal our URL and release the channel to public.

Please follow progress of Open Shop Channel on our Discord server.

**Comment by dakrk** [comment]
If you do want to experience the open shop channel, I'd download the repo, host it somewhere, then either patch the wad yourself (the file needs to be the same size as the original wad so the domain has to be the same length as the original) or setup a DNS that makes Wii shop domains (oss-auth.shop.wii.com, I think) point to the server that you're hosting the shop's files on

**Comment by dakrk** [comment]
As a DNS server, I'd personally recommend dnsmasq.
